# Generated by Django 5.1.1 on 2024-09-04 00:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="conteaudo",
        ),
        migrations.AddField(
            model_name="post",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
