# Generated by Django 5.1.1 on 2024-09-04 00:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_remove_post_conteaudo_post_conteudo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="resumo",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
