# Generated by Django 5.1.1 on 2024-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_alter_post_resumo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AddField(
            model_name="post",
            name="post_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
