# Generated by Django 5.1.1 on 2024-09-06 02:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_remove_post_id_post_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="capa",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
