# Generated by Django 5.1.1 on 2024-09-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_alter_post_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="capa",
            field=models.FilePathField(),
        ),
    ]
